### ISSUE TITLE
Complete the four items from Angel for Unit Testing that are supposed to be in the team report

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/againstHumanityTest#8]

**Comment by JoshuaVSherman** [comment]
you have some nice diagrams, but I'm not sure about this du path tests?

**Comment by jlangfor** [comment]
I was going to do full-path testing where I can and state/branch coverage where I can not. I am working on it now and should have something in the testing document as well as a write up in the actual document sometime today.
